#!/bin/bash
# Bash Menu Script Example

PS3='Please enter your choice: '
sub_options=("Option 1" "Option 2" "Option 3" "Quit")
select opt in "${sub_options[@]}"
do
    case $opt in
        "Option 1")
            echo "you chose choice 1"
            ;;
        "Option 2")
            echo "you chose choice 2"
            ;;
        "Option 3")
            echo "you chose choice $REPLY which is $opt"
            ;;
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
